### ISSUE TITLE
加载10000条数据

### ISSUE THREAD

**Issue by Allen-cxl** [xiangcman/LayoutManager-FlowLayout#27]
加载10000条数据，App直接ANR了。有什么办法解决的吗?

**Comment by xiangcman** [comment]
你把发生Anr的日志发给我

发自我的 iPhone

**Comment by Allen-cxl** [comment]
后来我重新看了下，又没有出现anr。出现了下面问题：
1.空指针crash
2.上下快速滑动会卡顿，布局会重叠
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Rect.bottom' on a null object reference at com.test.toastdemo.FlowLayoutManager.fill(FlowLayoutManager.java:191)
at com.test.toastdemo.FlowLayoutManager.scrollVerticallyBy(FlowLayoutManager.java:241)
 at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4680)

代码片段：
RecyclerView.setLayoutManager(new FlowLayoutManager());
RecyclerView.setAdapter(new RecycleViewAdapter(this, Data.foods()));
public static List<Data> foods(){
    List<Data> foods =new ArrayList<>();
    Data food = null;
    for (int i = 0 ; i < 10000 ; i++){
      food = new Data("recycle"+"("+i+")");
      foods.add(food);
    }
    return foods;
  }

**Comment by xiangcman** [comment]
具体加我qq吧 或者加群 1002326270

发自我的 iPhone
