### ISSUE TITLE
AndroidRuntime

### ISSUE THREAD

**Issue by decLH** [xiangcman/LayoutManager-FlowLayout#29]
.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.txunda.cropproduct.debug, PID: 25313
                                                                              java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Rect.top' on a null object reference
                                                                                  at com.library.flowlayout.FlowLayoutManager.formatAboveRow(FlowLayoutManager.java:234)
                                                                                  at com.library.flowlayout.FlowLayoutManager.onLayoutChildren(FlowLayoutManager.java:154)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
                                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
                                                                                  at android.view.View.layout(View.java:19659)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                                  at android.view.View.layout(View.java:19659)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                                  at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1165)
                                                                                  at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:850)
                                                                                  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:869)
                                                                                  at android.view.View.layout(View.java:19659)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                  at android.view.View.layout(View.java:19659)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                                  at android.view.View.layout(View.java:19659)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                  at android.view.View.layout(View.java:19659)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                                  at android.view.View.layout(View.java:19659)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                  at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
                                                                                  at android.view.View.layout(View.java:19659)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                  at android.os.Handler.handleCallback(Handler.java:790)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by decLH** [comment]
item数量超过一屏后会出现这个问题

**Comment by xiangcman** [comment]
你好，使用github最新的代码跑出来的问题吗，不要用依赖的形式，在时没遇到你这个问题额。
